packages:
  - packages/*

overrides:
  '@intlify/message-compiler': ^11.1.2

catalog:
  '@antfu/eslint-config': ^4.10.2
  '@antfu/ni': ^24.3.0
  '@antfu/utils': ^9.2.0
  '@arco-design/web-vue': ^2.57.0
  '@arco-plugins/vite-vue': ^1.4.5
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/svg-spinners': ^1.2.2
  '@internationalized/date': ^3.8.0
  '@intlify/eslint-plugin-vue-i18n': ^4.0.1
  '@modyfi/vite-plugin-yaml': ^1.1.1
  '@nuxt/eslint': 1.0.1
  '@nuxt/icon': 1.10.3
  '@nuxt/kit': ^3.16.2
  '@nuxtjs/color-mode': 3.5.2
  '@nuxtjs/i18n': 9.3.0
  '@pinia/nuxt': ^0.11.0
  '@rollup/plugin-commonjs': ^28.0.3
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rollup/plugin-typescript': ^12.1.2
  '@t3-oss/env-core': ^0.12.0
  '@tanstack/eslint-plugin-query': ^5.73.3
  '@tanstack/vue-form': ^1.6.3
  '@tanstack/vue-query': ^5.74.5
  '@tanstack/vue-query-devtools': ^5.74.5
  '@tanstack/vue-table': ^8.21.3
  '@turf/helpers': ^7.2.0
  '@turf/turf': ^7.2.0
  '@types/crypto-js': ^4.2.2
  '@types/geojson': ^7946.0.16
  '@types/lodash': ^4.17.16
  '@types/md5': ^2.3.5
  '@types/mockjs': ^1.0.10
  '@types/node': ^22.14.1
  '@types/nprogress': ^0.2.3
  '@types/sortablejs': ^1.15.8
  '@unhead/vue': ^2.0.8
  '@unocss/core': ^65.4.0
  '@unocss/eslint-plugin': ^66.0.0
  '@unocss/nuxt': 66.1.0-beta.3
  '@unocss/preset-web-fonts': 66.1.0-beta.3
  '@unocss/reset': 66.1.0-beta.3
  '@vee-validate/nuxt': ^4.15.0
  '@vee-validate/zod': ^4.15.0
  '@videojs-player/vue': ^1.0.0
  '@vitejs/plugin-vue': ^5.2.3
  '@vuemap/unplugin-resolver': ^2.0.1
  '@vuemap/vue-amap': ^2.1.11
  '@vuemap/vue-amap-extra': ^2.1.5
  '@vuemap/vue-amap-loca': ^2.1.2
  '@vueuse/components': ^13.1.0
  '@vueuse/core': ^13.1.0
  '@vueuse/integrations': ^13.1.0
  '@vueuse/nuxt': ^13.1.0
  '@vueuse/router': ^13.1.0
  '@vueuse/sound': ^2.1.3
  apipost-mock-gen: ^0.1.5
  axios: ^1.8.4
  browser-image-compression: ^2.0.2
  bumpp: ^10.1.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  core-js: ^3.41.0
  cropperjs: ^1.6.2
  cross-env: ^7.0.3
  crypto-js: ^4.2.0
  dotenv: ^16.5.0
  echarts: ^5.6.0
  eslint: ^9.25.0
  eslint-factory: ^0.1.2
  eslint-plugin-fix-later: ^2.1.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-unimport: ^0.1.2
  esno: ^4.8.0
  fuse.js: ^7.1.0
  https-localhost: ^4.7.1
  jiti: ^2.4.2
  jsonc-parser: ^3.3.1
  less: ^4.3.0
  lint-staged: ^15.5.1
  listhen: ^1.9.0
  lodash: ^4.17.21
  lucide-vue-next: ^0.503.0
  marked: ^15.0.8
  md5: ^2.3.0
  mockjs: ^1.1.0
  msw: ^2.7.5
  nanoid: ^5.1.5
  nprogress: ^0.2.0
  nuxt: ^3.16.2
  nuxt-lucide-icons: 1.0.5
  nuxt-vite-legacy: ^2.0.0
  nuxt-zod-i18n: 1.11.5
  ofetch: ^1.4.1
  pinia: ^3.0.2
  postcss-html: ^1.8.0
  promise-polyfill: 8.3.0
  qrcode: ^1.5.4
  radix-vue: ^1.9.17
  rehype-stringify: ^10.0.1
  reka-ui: 1.0.0-alpha.9
  remark: ^15.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  remark-stringify: ^11.0.0
  rollup: ^4.40.0
  rollup-plugin-visualizer: ^5.14.0
  simple-git-hooks: ^2.12.1
  taze: ^19.0.4
  typescript: ^5.8.3
  ufo: ^1.6.1
  unbuild: ^3.5.0
  undici: ^7.8.0
  unfetch: ^5.0.0
  unified: ^11.0.5
  unist-util-visit: ^5.0.0
  unocss: 66.1.0-beta.3
  unocss-preset-extra: ^0.5.3
  unplugin-auto-import: ^19.1.2
  unplugin-dist-zip: ^0.0.1
  unplugin-imagemin: ^0.6.7
  unplugin-inline-enum: ^0.3.1
  unplugin-unused: ^0.4.4
  unplugin-vue-components: ^28.5.0
  unplugin-vue-macros: ^2.14.5
  unplugin-vue-router: ^0.12.0
  vaul-vue: ^0.4.1
  vconsole: ^3.15.1
  vee-validate: ^4.15.0
  video.js: ^8.22.0
  viewerjs: ^1.11.7
  vite: ^6.3.2
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.3
  vite-plugin-imagemin: ^0.6.1
  vite-plugin-mkcert: ^1.17.8
  vite-plugin-mock: ^3.0.2
  vite-plugin-vue-devtools: ^7.7.5
  vite-plugin-vue-layouts: ^0.11.0
  vite-svg-loader: ^5.1.0
  vitest: ^3.1.2
  vue: ^3.5.13
  vue-echarts: ^7.0.3
  vue-i18n: ^10.0.7
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  whatwg-fetch: ^3.6.20
  zod: ^3.24.3
  zx: ^8.5.3
