/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarUploader: typeof import('./components/AvatarUploader.vue')['default']
    BindingPhone: typeof import('./components/BindingPhone.vue')['default']
    Block: typeof import('./components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./components/breadcrumb/index.vue')['default']
    Chart: typeof import('./components/chart/index.vue')['default']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    FileUploader: typeof import('./components/FileUploader.vue')['default']
    Footer: typeof import('./components/footer/index.vue')['default']
    FormWrapper: typeof import('./components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./components/global-setting/index.vue')['default']
    HoverCardArrow: typeof import('radix-vue')['HoverCardArrow']
    HoverCardContent: typeof import('radix-vue')['HoverCardContent']
    HoverCardPortal: typeof import('radix-vue')['HoverCardPortal']
    HoverCardRoot: typeof import('radix-vue')['HoverCardRoot']
    HoverCardTrigger: typeof import('radix-vue')['HoverCardTrigger']
    List: typeof import('./components/message-box/list.vue')['default']
    LoadingMask: typeof import('./components/LoadingMask.vue')['default']
    LoginBanner: typeof import('./components/login-banner/index.vue')['default']
    MapPicker: typeof import('./components/MapPicker.vue')['default']
    Menu: typeof import('./components/menu/index.vue')['default']
    MessageBox: typeof import('./components/message-box/index.vue')['default']
    MessageFileContent: typeof import('./components/MessageFileContent.vue')['default']
    MessageLocationContent: typeof import('./components/MessageLocationContent.vue')['default']
    MessagePictureContent: typeof import('./components/MessagePictureContent.vue')['default']
    MessageRevokeContent: typeof import('./components/MessageRevokeContent.vue')['default']
    MessageTextContent: typeof import('./components/MessageTextContent.vue')['default']
    MessageUnsupportedContent: typeof import('./components/MessageUnsupportedContent.vue')['default']
    MessageVideoContent: typeof import('./components/MessageVideoContent.vue')['default']
    MessageVoiceContent: typeof import('./components/MessageVoiceContent.vue')['default']
    Navbar: typeof import('./components/navbar/index.vue')['default']
    ResetSelfPasswordModal: typeof import('./components/ResetSelfPasswordModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfCard: typeof import('./components/SelfCard.vue')['default']
    SendSmsButton: typeof import('./components/SendSmsButton.vue')['default']
    TestTable: typeof import('./components/TestTable.vue')['default']
    TheCropper: typeof import('./components/TheCropper.vue')['default']
    TheModal: typeof import('./components/TheModal.vue')['default']
    ToolbarButton: typeof import('radix-vue')['ToolbarButton']
    ToolbarLink: typeof import('radix-vue')['ToolbarLink']
    ToolbarRoot: typeof import('radix-vue')['ToolbarRoot']
    ToolbarSeparator: typeof import('radix-vue')['ToolbarSeparator']
    VerifyImg: typeof import('./components/VerifyImg.vue')['default']
  }
}
