/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDeptMemberModal: typeof import('./components/AddDeptMemberModal.vue')['default']
    AddDeviceModal: typeof import('./components/AddDeviceModal.vue')['default']
    AvatarUploader: typeof import('./components/AvatarUploader.vue')['default']
    BindingPhone: typeof import('./components/BindingPhone.vue')['default']
    Breadcrumb: typeof import('./components/breadcrumb/index.vue')['default']
    ContactSelectTree: typeof import('./components/ContactSelectTree.vue')['default']
    CreateMemberModal: typeof import('./components/CreateMemberModal.vue')['default']
    DeleteMemberModal: typeof import('./components/DeleteMemberModal.vue')['default']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    EditDeviceModal: typeof import('./components/EditDeviceModal.vue')['default']
    EditMemberModal: typeof import('./components/EditMemberModal.vue')['default']
    FileUploader: typeof import('./components/FileUploader.vue')['default']
    Footer: typeof import('./components/footer/index.vue')['default']
    LoadingMask: typeof import('./components/LoadingMask.vue')['default']
    LoginBanner: typeof import('./components/login-banner/index.vue')['default']
    MapPicker: typeof import('./components/MapPicker.vue')['default']
    MemberTable: typeof import('./components/MemberTable.vue')['default']
    MessageFileContent: typeof import('./components/MessageFileContent.vue')['default']
    MessageLocationContent: typeof import('./components/MessageLocationContent.vue')['default']
    MessagePictureContent: typeof import('./components/MessagePictureContent.vue')['default']
    MessageRevokeContent: typeof import('./components/MessageRevokeContent.vue')['default']
    MessageTextContent: typeof import('./components/MessageTextContent.vue')['default']
    MessageUnsupportedContent: typeof import('./components/MessageUnsupportedContent.vue')['default']
    MessageVideoContent: typeof import('./components/MessageVideoContent.vue')['default']
    MessageVoiceContent: typeof import('./components/MessageVoiceContent.vue')['default']
    ModalTrigger: typeof import('./components/ModalTrigger.vue')['default']
    Navbar: typeof import('./components/navbar/index.vue')['default']
    ResetMemberPasswordModal: typeof import('./components/ResetMemberPasswordModal.vue')['default']
    ResetSelfPasswordModal: typeof import('./components/ResetSelfPasswordModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfCard: typeof import('./components/SelfCard.vue')['default']
    SendSmsButton: typeof import('./components/SendSmsButton.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    TestTable: typeof import('./components/TestTable.vue')['default']
    TheCropper: typeof import('./components/TheCropper.vue')['default']
    TheModal: typeof import('./components/TheModal.vue')['default']
    ToolbarButton: typeof import('radix-vue')['ToolbarButton']
    ToolbarLink: typeof import('radix-vue')['ToolbarLink']
    ToolbarRoot: typeof import('radix-vue')['ToolbarRoot']
    ToolbarSeparator: typeof import('radix-vue')['ToolbarSeparator']
    TreeMenu: typeof import('./components/TreeMenu.vue')['default']
    VerifyImg: typeof import('./components/VerifyImg.vue')['default']
  }
}
